### PR TITLE
fix: Navigation Bar - TypeScript Props

### LINKED ISSUE #22: fix: Navigation Bar - Typescript Props
https://reactnavigation.org/docs/typescript/

### PR DESCRIPTION
**Pull request by felixindrawan**
Closes #22

### CODE REVIEW

File: src/routes/types.tsx [hunk 1]
```diff
@@ -0,0 +1,74 @@
+import type {
+  CompositeNavigationProp,
+  CompositeScreenProps,
+  NavigatorScreenParams,
+} from '@react-navigation/native';
+import type { StackNavigationProp, StackScreenProps } from '@react-navigation/stack';
+import type { BottomTabNavigationProp, BottomTabScreenProps } from '@react-navigation/bottom-tabs';
+
+export type RootStackParamList = {
+  bottomTab: NavigatorScreenParams<BottomTabParamList>;
```
Comment (felixindrawan) [inline src/routes/types.tsx]: nit `[Route.BOTTOM_TAB]: NavigatorScreenParams`

File: src/routes/RootNavigator.tsx [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+const RootStack = createNativeStackNavigator<RootStackParamList>();
+
+const RootNavigator = () => {
+  return (
+    <NavigationContainer>
+      <RootStack.Navigator screenOptions={{ headerShown: false }}>
+        <RootStack.Screen
+          name={Route.BOTTOM_TAB}
+          component={BottomTab}
+          options={{ headerShown: false }}
```
Comment (felixindrawan) [inline src/routes/RootNavigator.tsx]: can remove

File: src/components/PageView/index.tsx [hunk 3]
```diff
@@ -1,19 +1,23 @@
...
 }
 
-export default function ScreenView({ children, headerProps }) {
+export default function ScreenView({ children, headerProps }: ScreenViewProps) {
+  const { currentTheme } = useTheme();
+
   return (
-    <View style={styles.container}>
+    <SafeAreaView
+      style={{ ...styles.container, backgroundColor: getBGColor(currentTheme), flex: 1 }}
```
Comment (felixindrawan) [inline src/components/PageView/index.tsx]: no need `flex: 1`

File: src/routes/stacks/SettingsStack.tsx [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+    <Stack.Navigator
+      screenOptions={{
+        headerShown: false,
+      }}
+      initialRouteName={Route.SETTINGS}
+    >
+      <Stack.Screen
+        name={Route.SETTINGS}
+        component={SettingsScreen}
+        options={{ headerShown: false }}
```
Comment (felixindrawan) [inline src/routes/stacks/SettingsStack.tsx]: can remove
